### PR TITLE
Refactored more stuff, didn't tackle the direction changing yet

### PR DESCRIPTION
**Pull request by rak1507**
Perhaps using complex numbers could make it straightforward? Not sure, it would also be a big change. What test cases should be added as well?

### CODE REVIEW

**Comment by clubby789** [comment]
Right now the test cases are just making sure that output matches with output from the original LaserLang. Ideally having some simpler programs, making sure every instruction is covered.

Not worked with complex numbers in Python before, could you explain how that would work here?

**Comment by rak1507** [comment]
Instead of the direction being [0, 1] it could just be i, or something. Not sure. Then some rotation is easier.

**Comment by clubby789** [comment]
Hmm, the reason I chose to implement it as a direct mapping of start->end direction is because there's so much variation in how the mirrors apply direction changes, that any generalisation of 'rotation' would end up as some spaghetti code. Storing it as a complex number seems like a bit of a hack, but also could work.

Alternatively, could use an enum. 

Again alternatively, could make a direction class/a more generic Vector2 class, to handle addition etc. Would also mean I could move all the mirror logic into that class and out of the main class.

**Comment by rak1507** [comment]
I feel like that would be slight overkill. Tomorrow if I haven't thought of a better idea I'll make a dict with lambdas for the arrows, I feel like there are simple one line solutions, I just haven't thought of them all yet. Certainly the arrows like > have easy solutions.

**Comment by PTK12** [comment]
i did lookup tables. i tried lambdas but the code is too chonky (gets a bit long and longer than lookup). ive made lookup for now but mebbe in the future someone could find a way to make the lambdas less chonky. could be possible with complex nums in the future as rak mentioned?

**Comment by clubby789** [comment]
Merging this because it all seems good.

**Pull request merged**
